/* ============ 产品数据（由 server/tools/build-data.js 自动生成，勿手改） ============
   素材：assets/real/（命名规范见 素材命名规范.md）
   标签：server/tools/labels.json（node server/tools/tag-items.js 生成）
   重新生成：node server/tools/build-data.js */

const ITEMS = [{"id":"f-daily-01-bottom","name":"黄色半身裙","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"半身裙","颜色":"黄色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-01-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"学院风","置信度":"高"}},
{"id":"f-daily-01-top","name":"黑色T恤","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"T恤","颜色":"黑色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-daily-02-bottom","name":"卡其色半身裙","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"半身裙","颜色":"卡其色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-daily-02-shoes","name":"日常鞋子","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"不确定","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-02-top","name":"白色衬衫","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-03-bottom","name":"棕色半身裙","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"半身裙","颜色":"棕色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-daily-03-shoes","name":"红色皮鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"红色","适用场景":"通勤","风格":"学院风","置信度":"高"}},
{"id":"f-daily-03-top","name":"米色T恤","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"T恤","颜色":"米色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-04-bottom","name":"蓝色短裤","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"短裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-04-shoes","name":"棕色凉鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"凉鞋","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-04-top","name":"蓝色衬衫","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-05-bottom","name":"米色半身裙","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"半身裙","颜色":"米色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-daily-05-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"学院风","置信度":"高"}},
{"id":"f-daily-05-top","name":"蓝色衬衫","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-06-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-daily-06-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-daily-06-top","name":"黄色T恤","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"T恤","颜色":"黄色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"f-daily-07-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-07-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-07-top","name":"黑色衬衫","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"黑色","适用场景":"通勤","风格":"学院风","置信度":"高"}},
{"id":"f-daily-08-bottom","name":"白色长裤","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-08-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"f-daily-08-top","name":"灰色针织衫","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"针织衫","颜色":"灰色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-09-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-09-shoes","name":"白色运动鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-09-top","name":"绿色针织衫","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"针织衫","颜色":"绿色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-daily-10-bottom","name":"蓝色长裤","cat":"下装","gender":"f","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-10-shoes","name":"黑色运动鞋","cat":"鞋子","gender":"f","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-daily-10-top","name":"红色T恤","cat":"上衣","gender":"f","scene":"日常","ph":"tee","labels":{"类别":"T恤","颜色":"红色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-date-01-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"约会","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-01-shoes","name":"白色凉鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"凉鞋","颜色":"白色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-date-01-top","name":"白色针织衫","cat":"上衣","gender":"f","scene":"约会","ph":"tee","labels":{"类别":"针织衫","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-date-02-bottom","name":"米色半身裙","cat":"下装","gender":"f","scene":"约会","ph":"pants","labels":{"类别":"半身裙","颜色":"米色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-date-02-shoes","name":"米色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-02-top","name":"棕色针织衫","cat":"上衣","gender":"f","scene":"约会","ph":"tee","labels":{"类别":"针织衫","颜色":"棕色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-date-03-dress","name":"白色连衣裙","cat":"连体裙","gender":"f","scene":"约会","ph":"dress","labels":{"类别":"连衣裙","颜色":"白色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-03-shoes","name":"米色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"米色","适用场景":"约会","风格":"法式","置信度":"高"}},
{"id":"f-date-04-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"约会","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-date-04-shoes","name":"米色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-04-top","name":"白色衬衫","cat":"上衣","gender":"f","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"白色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-05-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"约会","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-date-05-shoes","name":"多色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"多色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"f-date-05-top","name":"绿色T恤","cat":"上衣","gender":"f","scene":"约会","ph":"tee","labels":{"类别":"T恤","颜色":"绿色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-date-06-dress","name":"紫色连衣裙","cat":"连体裙","gender":"f","scene":"约会","ph":"dress","labels":{"类别":"连衣裙","颜色":"紫色","适用场景":"约会","风格":"法式","置信度":"高"}},
{"id":"f-date-06-shoes","name":"白色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"白色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-07-dress","name":"米色连衣裙","cat":"连体裙","gender":"f","scene":"约会","ph":"dress","labels":{"类别":"连衣裙","颜色":"米色","适用场景":"其他","风格":"简约","置信度":"高"}},
{"id":"f-date-07-shoes","name":"银色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"银色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-date-08-bottom","name":"蓝色长裤","cat":"下装","gender":"f","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-date-08-shoes","name":"白色运动鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-date-08-top","name":"红色针织衫","cat":"上衣","gender":"f","scene":"约会","ph":"tee","labels":{"类别":"针织衫","颜色":"红色","适用场景":"约会","风格":"甜美","置信度":"高"}},
{"id":"f-date-09-dress","name":"灰色连衣裙","cat":"连体裙","gender":"f","scene":"约会","ph":"dress","labels":{"类别":"连衣裙","颜色":"灰色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-09-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-date-10-dress","name":"多色连衣裙","cat":"连体裙","gender":"f","scene":"约会","ph":"dress","labels":{"类别":"连衣裙","颜色":"多色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-date-10-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-travel-01-dress","name":"绿色连衣裙","cat":"连体裙","gender":"f","scene":"旅行","ph":"dress","labels":{"类别":"连衣裙","颜色":"绿色","适用场景":"约会","风格":"法式","置信度":"高"}},
{"id":"f-travel-01-shoes","name":"旅行鞋子","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"不确定","颜色":"米色","适用场景":"日常","风格":"甜美","置信度":"中"}},
{"id":"f-travel-02-bottom","name":"棕色半身裙","cat":"下装","gender":"f","scene":"旅行","ph":"pants","labels":{"类别":"半身裙","颜色":"棕色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-travel-02-shoes","name":"棕色靴子","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"靴子","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-travel-02-top","name":"棕色T恤","cat":"上衣","gender":"f","scene":"旅行","ph":"tee","labels":{"类别":"T恤","颜色":"棕色","适用场景":"日常","风格":"韩系","置信度":"高"}},
{"id":"f-travel-03-dress","name":"米色连衣裙","cat":"连体裙","gender":"f","scene":"旅行","ph":"dress","labels":{"类别":"连衣裙","颜色":"米色","适用场景":"约会","风格":"法式","置信度":"高"}},
{"id":"f-travel-03-shoes","name":"米色皮鞋","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"米色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-travel-04-dress","name":"米色连衣裙","cat":"连体裙","gender":"f","scene":"旅行","ph":"dress","labels":{"类别":"连衣裙","颜色":"米色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-travel-04-shoes","name":"黄色凉鞋","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"凉鞋","颜色":"黄色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-travel-05-dress","name":"白色连衣裙","cat":"连体裙","gender":"f","scene":"旅行","ph":"dress","labels":{"类别":"连衣裙","颜色":"白色","适用场景":"旅行","风格":"法式","置信度":"高"}},
{"id":"f-travel-05-shoes","name":"旅行鞋子","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"不确定","颜色":"米色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-travel-06-bottom","name":"蓝色长裤","cat":"下装","gender":"f","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-travel-06-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-travel-06-top","name":"黄色连衣裙","cat":"上衣","gender":"f","scene":"旅行","ph":"tee","labels":{"类别":"连衣裙","颜色":"黄色","适用场景":"约会","风格":"法式","置信度":"高"}},
{"id":"f-travel-07-bottom","name":"白色短裤","cat":"下装","gender":"f","scene":"旅行","ph":"pants","labels":{"类别":"短裤","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-travel-07-shoes","name":"旅行鞋子","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"不确定","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-travel-07-top","name":"米色衬衫","cat":"上衣","gender":"f","scene":"旅行","ph":"tee","labels":{"类别":"衬衫","颜色":"米色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-travel-08-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"旅行","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-travel-08-shoes","name":"黄色皮鞋","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黄色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-travel-08-top","name":"白色T恤","cat":"上衣","gender":"f","scene":"旅行","ph":"tee","labels":{"类别":"T恤","颜色":"白色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-travel-09-bottom","name":"粉色半身裙","cat":"下装","gender":"f","scene":"旅行","ph":"pants","labels":{"类别":"半身裙","颜色":"粉色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-travel-09-shoes","name":"米色凉鞋","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"凉鞋","颜色":"米色","适用场景":"约会","风格":"甜美","置信度":"高"}},
{"id":"f-travel-09-top","name":"粉色T恤","cat":"上衣","gender":"f","scene":"旅行","ph":"tee","labels":{"类别":"T恤","颜色":"粉色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-travel-10-bottom","name":"蓝色长裤","cat":"下装","gender":"f","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-travel-10-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"旅行","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-travel-10-top","name":"米色针织衫","cat":"上衣","gender":"f","scene":"旅行","ph":"tee","labels":{"类别":"针织衫","颜色":"米色","适用场景":"约会","风格":"甜美","置信度":"高"}},
{"id":"f-work-01-bottom","name":"白色长裤","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"白色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-work-01-shoes","name":"绿色皮鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"绿色","适用场景":"日常","风格":"法式","置信度":"高"}},
{"id":"f-work-01-top","name":"绿色衬衫","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"衬衫","颜色":"绿色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-work-02-bottom","name":"蓝色长裤","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-work-02-shoes","name":"白色运动鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-work-02-top","name":"蓝色T恤","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"T恤","颜色":"蓝色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-work-03-bottom","name":"蓝色半身裙","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"半身裙","颜色":"蓝色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-work-03-shoes","name":"粉色皮鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"粉色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-work-03-top","name":"蓝色T恤","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"T恤","颜色":"蓝色","适用场景":"日常","风格":"甜美","置信度":"高"}},
{"id":"f-work-04-bottom","name":"米色半身裙","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"半身裙","颜色":"米色","适用场景":"通勤","风格":"法式","置信度":"高"}},
{"id":"f-work-04-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"f-work-04-top","name":"米色西装","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"西装","颜色":"米色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"f-work-05-dress","name":"黄色连衣裙","cat":"连体裙","gender":"f","scene":"通勤","ph":"dress","labels":{"类别":"连衣裙","颜色":"黄色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-work-05-shoes","name":"米色皮鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-work-06-bottom","name":"蓝色长裤","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-work-06-shoes","name":"黑色凉鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"凉鞋","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-work-06-top","name":"蓝色衬衫","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-work-07-bottom","name":"白色半身裙","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"半身裙","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-work-07-shoes","name":"黑色凉鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"凉鞋","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"f-work-07-top","name":"红色T恤","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"T恤","颜色":"红色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"f-work-08-bottom","name":"黑色长裤","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"f-work-08-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"f-work-08-top","name":"蓝色衬衫","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"f-work-10-bottom","name":"棕色长裤","cat":"下装","gender":"f","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-work-10-shoes","name":"通勤鞋子","cat":"鞋子","gender":"f","scene":"通勤","ph":"sneaker","labels":{"类别":"不确定","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"f-work-10-top","name":"黄色T恤","cat":"上衣","gender":"f","scene":"通勤","ph":"tee","labels":{"类别":"T恤","颜色":"黄色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-01-bottom","name":"蓝色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-01-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-daily-01-top","name":"黑色针织衫","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"针织衫","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-02-bottom","name":"卡其色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"卡其色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-02-shoes","name":"黑色拖鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"拖鞋","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-02-top","name":"蓝色衬衫","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-03-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-03-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-03-top","name":"黑色T恤","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"T恤","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-04-bottom","name":"米色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"米色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-04-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-04-top","name":"绿色T恤","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"T恤","颜色":"绿色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-05-bottom","name":"白色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-05-shoes","name":"黑色运动鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"黑色","适用场景":"其他","风格":"运动","置信度":"高"}},
{"id":"m-daily-05-top","name":"蓝色衬衫","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-06-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"m-daily-06-shoes","name":"黑色运动鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"黑色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"m-daily-06-top","name":"黑色外套","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"外套","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-07-bottom","name":"绿色短裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"短裤","颜色":"绿色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-07-shoes","name":"灰色运动鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"灰色","适用场景":"日常","风格":"运动","置信度":"高"}},
{"id":"m-daily-07-top","name":"黑色T恤","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"T恤","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-08-bottom","name":"白色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-08-shoes","name":"日常鞋子","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"不确定","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-08-top","name":"蓝色针织衫","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"针织衫","颜色":"蓝色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-09-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-daily-09-shoes","name":"黑色运动鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-09-top","name":"蓝色衬衫","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-10-bottom","name":"白色短裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"短裤","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-10-shoes","name":"日常鞋子","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"不确定","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-daily-10-top","name":"灰色针织衫","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"针织衫","颜色":"灰色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-11-bottom","name":"卡其色长裤","cat":"下装","gender":"m","scene":"日常","ph":"pants","labels":{"类别":"长裤","颜色":"卡其色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-11-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"日常","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-daily-11-top","name":"黑色衬衫","cat":"上衣","gender":"m","scene":"日常","ph":"tee","labels":{"类别":"衬衫","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-date-01-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-01-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"休闲","置信度":"高"}},
{"id":"m-date-01-top","name":"蓝色衬衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"m-date-02-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-02-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"休闲","置信度":"高"}},
{"id":"m-date-02-top","name":"白色T恤","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"T恤","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-date-03-bottom","name":"米色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-03-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-date-03-top","name":"米色衬衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-04-bottom","name":"蓝色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-date-04-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-date-04-top","name":"灰色衬衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"灰色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-05-bottom","name":"米色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-05-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-date-05-top","name":"棕色针织衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"针织衫","颜色":"棕色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-date-06-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-06-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-date-06-top","name":"棕色衬衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-date-07-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-07-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-07-top","name":"蓝色T恤","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"T恤","颜色":"蓝色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-date-08-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-08-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-date-08-top","name":"蓝色衬衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-date-09-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-09-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"通勤","风格":"休闲","置信度":"高"}},
{"id":"m-date-09-top","name":"黑色衬衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-date-10-bottom","name":"米色长裤","cat":"下装","gender":"m","scene":"约会","ph":"pants","labels":{"类别":"长裤","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-date-10-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"约会","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-date-10-top","name":"黑色衬衫","cat":"上衣","gender":"m","scene":"约会","ph":"tee","labels":{"类别":"衬衫","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-travel-01-bottom","name":"棕色长裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-01-shoes","name":"米色皮鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"米色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-01-top","name":"绿色外套","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"外套","颜色":"绿色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-02-bottom","name":"白色短裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"短裤","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-02-shoes","name":"旅行鞋子","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"不确定","颜色":"米色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-02-top","name":"米色衬衫","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"衬衫","颜色":"米色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-travel-03-bottom","name":"棕色长裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-03-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-03-top","name":"棕色衬衫","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"衬衫","颜色":"棕色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-travel-04-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-travel-04-shoes","name":"黑色皮鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-04-top","name":"卡其色针织衫","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"针织衫","颜色":"卡其色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-05-bottom","name":"灰色短裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"短裤","颜色":"灰色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-05-shoes","name":"黑色拖鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"拖鞋","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"中"}},
{"id":"m-travel-05-top","name":"黑色卫衣","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"卫衣","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-06-bottom","name":"米色长裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"米色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-travel-06-shoes","name":"米色运动鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"米色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-06-top","name":"棕色衬衫","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"衬衫","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-07-bottom","name":"蓝色长裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-07-shoes","name":"黑色运动鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"黑色","适用场景":"其他","风格":"运动","置信度":"高"}},
{"id":"m-travel-07-top","name":"米色外套","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"外套","颜色":"米色","适用场景":"旅行","风格":"户外","置信度":"高"}},
{"id":"m-travel-08-bottom","name":"灰色长裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"长裤","颜色":"灰色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-08-shoes","name":"卡其色运动鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"卡其色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-08-top","name":"黑色卫衣","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"卫衣","颜色":"黑色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"m-travel-09-bottom","name":"卡其色短裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"短裤","颜色":"卡其色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-09-shoes","name":"棕色运动鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"棕色","适用场景":"旅行","风格":"户外","置信度":"高"}},
{"id":"m-travel-09-top","name":"绿色T恤","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"T恤","颜色":"绿色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-10-bottom","name":"多色短裤","cat":"下装","gender":"m","scene":"旅行","ph":"pants","labels":{"类别":"短裤","颜色":"多色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-travel-10-shoes","name":"灰色运动鞋","cat":"鞋子","gender":"m","scene":"旅行","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"灰色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"m-travel-10-top","name":"黄色外套","cat":"上衣","gender":"m","scene":"旅行","ph":"tee","labels":{"类别":"外套","颜色":"黄色","适用场景":"日常","风格":"街头","置信度":"高"}},
{"id":"m-work-01-bottom","name":"灰色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"灰色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-01-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-work-01-top","name":"黑色针织衫","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"针织衫","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-work-02-bottom","name":"灰色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"灰色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-work-02-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-02-top","name":"灰色西装","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"西装","颜色":"灰色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-03-bottom","name":"卡其色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"卡其色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-work-03-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-work-03-top","name":"棕色针织衫","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"针织衫","颜色":"棕色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-work-04-bottom","name":"绿色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"绿色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-04-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-work-04-top","name":"米色外套","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"外套","颜色":"米色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-work-05-bottom","name":"蓝色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"蓝色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-05-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-05-top","name":"绿色衬衫","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"衬衫","颜色":"绿色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-work-06-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-06-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-work-06-top","name":"灰色西装","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"西装","颜色":"灰色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-work-07-bottom","name":"灰色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"灰色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-07-shoes","name":"棕色皮鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"皮鞋","颜色":"棕色","适用场景":"通勤","风格":"商务","置信度":"高"}},
{"id":"m-work-07-top","name":"黑色衬衫","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"衬衫","颜色":"黑色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-work-08-bottom","name":"黑色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"黑色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-work-08-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-work-08-top","name":"蓝色针织衫","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"针织衫","颜色":"蓝色","适用场景":"日常","风格":"学院风","置信度":"高"}},
{"id":"m-work-09-bottom","name":"米色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-work-09-shoes","name":"米色运动鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"米色","适用场景":"日常","风格":"休闲","置信度":"高"}},
{"id":"m-work-09-top","name":"蓝色衬衫","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"衬衫","颜色":"蓝色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-work-10-bottom","name":"米色长裤","cat":"下装","gender":"m","scene":"通勤","ph":"pants","labels":{"类别":"长裤","颜色":"米色","适用场景":"通勤","风格":"简约","置信度":"高"}},
{"id":"m-work-10-shoes","name":"白色运动鞋","cat":"鞋子","gender":"m","scene":"通勤","ph":"sneaker","labels":{"类别":"运动鞋","颜色":"白色","适用场景":"日常","风格":"简约","置信度":"高"}},
{"id":"m-work-10-top","name":"黑色针织衫","cat":"上衣","gender":"m","scene":"通勤","ph":"tee","labels":{"类别":"针织衫","颜色":"黑色","适用场景":"日常","风格":"简约","置信度":"高"}}];

const CATS = ["全部", "上衣", "下装", "鞋子", "连体裙"];

const SCENES = [
  { key: "全部", icon: "✨" },
  { key: "通勤", icon: "💼" },
  { key: "约会", icon: "🌹" },
  { key: "旅行", icon: "🧳" },
  { key: "日常", icon: "☀️" },
  { key: "其他", icon: "🏷️" },
];

const OUTFITS = [{"id":"f-daily-01","name":"日常搭配 01","scene":"日常","gender":"f","items":["f-daily-01-top","f-daily-01-bottom","f-daily-01-shoes"]},
{"id":"f-daily-02","name":"日常搭配 02","scene":"日常","gender":"f","items":["f-daily-02-top","f-daily-02-bottom","f-daily-02-shoes"]},
{"id":"f-daily-03","name":"日常搭配 03","scene":"日常","gender":"f","items":["f-daily-03-top","f-daily-03-bottom","f-daily-03-shoes"]},
{"id":"f-daily-04","name":"日常搭配 04","scene":"日常","gender":"f","items":["f-daily-04-top","f-daily-04-bottom","f-daily-04-shoes"]},
{"id":"f-daily-05","name":"日常搭配 05","scene":"日常","gender":"f","items":["f-daily-05-top","f-daily-05-bottom","f-daily-05-shoes"]},
{"id":"f-daily-06","name":"日常搭配 06","scene":"日常","gender":"f","items":["f-daily-06-top","f-daily-06-bottom","f-daily-06-shoes"]},
{"id":"f-daily-07","name":"日常搭配 07","scene":"日常","gender":"f","items":["f-daily-07-top","f-daily-07-bottom","f-daily-07-shoes"]},
{"id":"f-daily-08","name":"日常搭配 08","scene":"日常","gender":"f","items":["f-daily-08-top","f-daily-08-bottom","f-daily-08-shoes"]},
{"id":"f-daily-09","name":"日常搭配 09","scene":"日常","gender":"f","items":["f-daily-09-top","f-daily-09-bottom","f-daily-09-shoes"]},
{"id":"f-daily-10","name":"日常搭配 10","scene":"日常","gender":"f","items":["f-daily-10-top","f-daily-10-bottom","f-daily-10-shoes"]},
{"id":"f-date-01","name":"约会搭配 01","scene":"约会","gender":"f","items":["f-date-01-top","f-date-01-bottom","f-date-01-shoes"]},
{"id":"f-date-02","name":"约会搭配 02","scene":"约会","gender":"f","items":["f-date-02-top","f-date-02-bottom","f-date-02-shoes"]},
{"id":"f-date-03","name":"约会搭配 03","scene":"约会","gender":"f","items":["f-date-03-dress","f-date-03-shoes"]},
{"id":"f-date-04","name":"约会搭配 04","scene":"约会","gender":"f","items":["f-date-04-top","f-date-04-bottom","f-date-04-shoes"]},
{"id":"f-date-05","name":"约会搭配 05","scene":"约会","gender":"f","items":["f-date-05-top","f-date-05-bottom","f-date-05-shoes"]},
{"id":"f-date-06","name":"约会搭配 06","scene":"约会","gender":"f","items":["f-date-06-dress","f-date-06-shoes"]},
{"id":"f-date-07","name":"约会搭配 07","scene":"约会","gender":"f","items":["f-date-07-dress","f-date-07-shoes"]},
{"id":"f-date-08","name":"约会搭配 08","scene":"约会","gender":"f","items":["f-date-08-top","f-date-08-bottom","f-date-08-shoes"]},
{"id":"f-date-09","name":"约会搭配 09","scene":"约会","gender":"f","items":["f-date-09-dress","f-date-09-shoes"]},
{"id":"f-date-10","name":"约会搭配 10","scene":"约会","gender":"f","items":["f-date-10-dress","f-date-10-shoes"]},
{"id":"f-travel-01","name":"旅行搭配 01","scene":"旅行","gender":"f","items":["f-travel-01-dress","f-travel-01-shoes"]},
{"id":"f-travel-02","name":"旅行搭配 02","scene":"旅行","gender":"f","items":["f-travel-02-top","f-travel-02-bottom","f-travel-02-shoes"]},
{"id":"f-travel-03","name":"旅行搭配 03","scene":"旅行","gender":"f","items":["f-travel-03-dress","f-travel-03-shoes"]},
{"id":"f-travel-04","name":"旅行搭配 04","scene":"旅行","gender":"f","items":["f-travel-04-dress","f-travel-04-shoes"]},
{"id":"f-travel-05","name":"旅行搭配 05","scene":"旅行","gender":"f","items":["f-travel-05-dress","f-travel-05-shoes"]},
{"id":"f-travel-06","name":"旅行搭配 06","scene":"旅行","gender":"f","items":["f-travel-06-top","f-travel-06-bottom","f-travel-06-shoes"]},
{"id":"f-travel-07","name":"旅行搭配 07","scene":"旅行","gender":"f","items":["f-travel-07-top","f-travel-07-bottom","f-travel-07-shoes"]},
{"id":"f-travel-08","name":"旅行搭配 08","scene":"旅行","gender":"f","items":["f-travel-08-top","f-travel-08-bottom","f-travel-08-shoes"]},
{"id":"f-travel-09","name":"旅行搭配 09","scene":"旅行","gender":"f","items":["f-travel-09-top","f-travel-09-bottom","f-travel-09-shoes"]},
{"id":"f-travel-10","name":"旅行搭配 10","scene":"旅行","gender":"f","items":["f-travel-10-top","f-travel-10-bottom","f-travel-10-shoes"]},
{"id":"f-work-01","name":"通勤搭配 01","scene":"通勤","gender":"f","items":["f-work-01-top","f-work-01-bottom","f-work-01-shoes"]},
{"id":"f-work-02","name":"通勤搭配 02","scene":"通勤","gender":"f","items":["f-work-02-top","f-work-02-bottom","f-work-02-shoes"]},
{"id":"f-work-03","name":"通勤搭配 03","scene":"通勤","gender":"f","items":["f-work-03-top","f-work-03-bottom","f-work-03-shoes"]},
{"id":"f-work-04","name":"通勤搭配 04","scene":"通勤","gender":"f","items":["f-work-04-top","f-work-04-bottom","f-work-04-shoes"]},
{"id":"f-work-05","name":"通勤搭配 05","scene":"通勤","gender":"f","items":["f-work-05-dress","f-work-05-shoes"]},
{"id":"f-work-06","name":"通勤搭配 06","scene":"通勤","gender":"f","items":["f-work-06-top","f-work-06-bottom","f-work-06-shoes"]},
{"id":"f-work-07","name":"通勤搭配 07","scene":"通勤","gender":"f","items":["f-work-07-top","f-work-07-bottom","f-work-07-shoes"]},
{"id":"f-work-08","name":"通勤搭配 08","scene":"通勤","gender":"f","items":["f-work-08-top","f-work-08-bottom","f-work-08-shoes"]},
{"id":"f-work-10","name":"通勤搭配 10","scene":"通勤","gender":"f","items":["f-work-10-top","f-work-10-bottom","f-work-10-shoes"]},
{"id":"m-daily-01","name":"日常搭配 01","scene":"日常","gender":"m","items":["m-daily-01-top","m-daily-01-bottom","m-daily-01-shoes"]},
{"id":"m-daily-02","name":"日常搭配 02","scene":"日常","gender":"m","items":["m-daily-02-top","m-daily-02-bottom","m-daily-02-shoes"]},
{"id":"m-daily-03","name":"日常搭配 03","scene":"日常","gender":"m","items":["m-daily-03-top","m-daily-03-bottom","m-daily-03-shoes"]},
{"id":"m-daily-04","name":"日常搭配 04","scene":"日常","gender":"m","items":["m-daily-04-top","m-daily-04-bottom","m-daily-04-shoes"]},
{"id":"m-daily-05","name":"日常搭配 05","scene":"日常","gender":"m","items":["m-daily-05-top","m-daily-05-bottom","m-daily-05-shoes"]},
{"id":"m-daily-06","name":"日常搭配 06","scene":"日常","gender":"m","items":["m-daily-06-top","m-daily-06-bottom","m-daily-06-shoes"]},
{"id":"m-daily-07","name":"日常搭配 07","scene":"日常","gender":"m","items":["m-daily-07-top","m-daily-07-bottom","m-daily-07-shoes"]},
{"id":"m-daily-08","name":"日常搭配 08","scene":"日常","gender":"m","items":["m-daily-08-top","m-daily-08-bottom","m-daily-08-shoes"]},
{"id":"m-daily-09","name":"日常搭配 09","scene":"日常","gender":"m","items":["m-daily-09-top","m-daily-09-bottom","m-daily-09-shoes"]},
{"id":"m-daily-10","name":"日常搭配 10","scene":"日常","gender":"m","items":["m-daily-10-top","m-daily-10-bottom","m-daily-10-shoes"]},
{"id":"m-daily-11","name":"日常搭配 11","scene":"日常","gender":"m","items":["m-daily-11-top","m-daily-11-bottom","m-daily-11-shoes"]},
{"id":"m-date-01","name":"约会搭配 01","scene":"约会","gender":"m","items":["m-date-01-top","m-date-01-bottom","m-date-01-shoes"]},
{"id":"m-date-02","name":"约会搭配 02","scene":"约会","gender":"m","items":["m-date-02-top","m-date-02-bottom","m-date-02-shoes"]},
{"id":"m-date-03","name":"约会搭配 03","scene":"约会","gender":"m","items":["m-date-03-top","m-date-03-bottom","m-date-03-shoes"]},
{"id":"m-date-04","name":"约会搭配 04","scene":"约会","gender":"m","items":["m-date-04-top","m-date-04-bottom","m-date-04-shoes"]},
{"id":"m-date-05","name":"约会搭配 05","scene":"约会","gender":"m","items":["m-date-05-top","m-date-05-bottom","m-date-05-shoes"]},
{"id":"m-date-06","name":"约会搭配 06","scene":"约会","gender":"m","items":["m-date-06-top","m-date-06-bottom","m-date-06-shoes"]},
{"id":"m-date-07","name":"约会搭配 07","scene":"约会","gender":"m","items":["m-date-07-top","m-date-07-bottom","m-date-07-shoes"]},
{"id":"m-date-08","name":"约会搭配 08","scene":"约会","gender":"m","items":["m-date-08-top","m-date-08-bottom","m-date-08-shoes"]},
{"id":"m-date-09","name":"约会搭配 09","scene":"约会","gender":"m","items":["m-date-09-top","m-date-09-bottom","m-date-09-shoes"]},
{"id":"m-date-10","name":"约会搭配 10","scene":"约会","gender":"m","items":["m-date-10-top","m-date-10-bottom","m-date-10-shoes"]},
{"id":"m-travel-01","name":"旅行搭配 01","scene":"旅行","gender":"m","items":["m-travel-01-top","m-travel-01-bottom","m-travel-01-shoes"]},
{"id":"m-travel-02","name":"旅行搭配 02","scene":"旅行","gender":"m","items":["m-travel-02-top","m-travel-02-bottom","m-travel-02-shoes"]},
{"id":"m-travel-03","name":"旅行搭配 03","scene":"旅行","gender":"m","items":["m-travel-03-top","m-travel-03-bottom","m-travel-03-shoes"]},
{"id":"m-travel-04","name":"旅行搭配 04","scene":"旅行","gender":"m","items":["m-travel-04-top","m-travel-04-bottom","m-travel-04-shoes"]},
{"id":"m-travel-05","name":"旅行搭配 05","scene":"旅行","gender":"m","items":["m-travel-05-top","m-travel-05-bottom","m-travel-05-shoes"]},
{"id":"m-travel-06","name":"旅行搭配 06","scene":"旅行","gender":"m","items":["m-travel-06-top","m-travel-06-bottom","m-travel-06-shoes"]},
{"id":"m-travel-07","name":"旅行搭配 07","scene":"旅行","gender":"m","items":["m-travel-07-top","m-travel-07-bottom","m-travel-07-shoes"]},
{"id":"m-travel-08","name":"旅行搭配 08","scene":"旅行","gender":"m","items":["m-travel-08-top","m-travel-08-bottom","m-travel-08-shoes"]},
{"id":"m-travel-09","name":"旅行搭配 09","scene":"旅行","gender":"m","items":["m-travel-09-top","m-travel-09-bottom","m-travel-09-shoes"]},
{"id":"m-travel-10","name":"旅行搭配 10","scene":"旅行","gender":"m","items":["m-travel-10-top","m-travel-10-bottom","m-travel-10-shoes"]},
{"id":"m-work-01","name":"通勤搭配 01","scene":"通勤","gender":"m","items":["m-work-01-top","m-work-01-bottom","m-work-01-shoes"]},
{"id":"m-work-02","name":"通勤搭配 02","scene":"通勤","gender":"m","items":["m-work-02-top","m-work-02-bottom","m-work-02-shoes"]},
{"id":"m-work-03","name":"通勤搭配 03","scene":"通勤","gender":"m","items":["m-work-03-top","m-work-03-bottom","m-work-03-shoes"]},
{"id":"m-work-04","name":"通勤搭配 04","scene":"通勤","gender":"m","items":["m-work-04-top","m-work-04-bottom","m-work-04-shoes"]},
{"id":"m-work-05","name":"通勤搭配 05","scene":"通勤","gender":"m","items":["m-work-05-top","m-work-05-bottom","m-work-05-shoes"]},
{"id":"m-work-06","name":"通勤搭配 06","scene":"通勤","gender":"m","items":["m-work-06-top","m-work-06-bottom","m-work-06-shoes"]},
{"id":"m-work-07","name":"通勤搭配 07","scene":"通勤","gender":"m","items":["m-work-07-top","m-work-07-bottom","m-work-07-shoes"]},
{"id":"m-work-08","name":"通勤搭配 08","scene":"通勤","gender":"m","items":["m-work-08-top","m-work-08-bottom","m-work-08-shoes"]},
{"id":"m-work-09","name":"通勤搭配 09","scene":"通勤","gender":"m","items":["m-work-09-top","m-work-09-bottom","m-work-09-shoes"]},
{"id":"m-work-10","name":"通勤搭配 10","scene":"通勤","gender":"m","items":["m-work-10-top","m-work-10-bottom","m-work-10-shoes"]}];

/* 新用户默认衣橱（女生/男生日常各两套的单品） */
const STARTER_WARDROBE = ["f-daily-01-bottom","f-daily-01-shoes","f-daily-01-top","f-daily-02-bottom","f-daily-02-shoes","f-daily-02-top","m-daily-01-bottom","m-daily-01-shoes","m-daily-01-top","m-daily-02-bottom","m-daily-02-shoes","m-daily-02-top"];

/* 预设虚拟模特：产品定义只有一个默认款，不可切换其他虚拟模特 */
const PRESET_MODELS = [
  { id: "m1", name: "默认模特", shape: "" },
];

const JOBS = {
  "学生": ["高中生", "大学生"],
  "职业": ["教师 / 教授", "软件工程师", "设计师", "产品经理", "创意工作者",
          "市场营销", "咨询", "律师", "投资银行从业者", "人力资源",
          "护士 / 医疗从业者", "自由职业者", "创业者", "公务员",
          "全职父母", "退休人员", "其他"],
};
